server:
  domain: user
  version: 1.0
  jwtSecret: 38324
  grpcAddress: "127.0.0.1:10001"

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3309
  database: grpc_todo_list
  username: root
  password: 123456
  charset: utf8mb4

etcd:
  address: 127.0.0.1:2379

redis:
  address: 192.168.43.223
  port:6379
  password:000415